#!/bin/bash
# Deny Edit/Write on an agent file that is generated from a shared source.
#
# The generated <name>.md is what Claude Code loads, so editing it works right
# up until someone runs the build, which overwrites it with no warning. The
# rule lives in <name>.src.md (one agent) or shared/base.md (all of them).
#
# Only blocks files that actually carry the GENERATED banner, so a hand-written
# agent, a .src.md, shared/base.md and every SKILL.md stay editable.

payload=$(cat)
f=$(printf '%s' "$payload" | jq -r '.tool_input.file_path // empty')
[ -z "$f" ] && exit 0

case "$f" in
  # Set AGENTS_ROOT_MATCH to a fragment of your own agents path.
  ${AGENTS_ROOT_MATCH:-*"/agents/"}*.md) ;;
  *) exit 0 ;;
esac

case "$f" in
  *.src.md|*/shared/base.md|*/SKILL.md) exit 0 ;;
esac

[ -f "$f" ] && grep -q "GENERATED by scripts/build_agents.py" "$f" || exit 0

src="${f%.md}.src.md"
jq -n --arg f "$(basename "$f")" --arg src "$(basename "$src")" '{
  hookSpecificOutput: {
    hookEventName: "PreToolUse",
    permissionDecision: "deny",
    permissionDecisionReason: ("\($f) is generated: the next run of build_agents.py overwrites anything edited here. Edit \($src) for this agent alone, or shared/base.md for every agent, then run: python3 scripts/build_agents.py")
  }
}'
