#!/usr/bin/env python3
"""Audit a multi-agent system for the gaps that stop it from being adaptive.

Point it at a directory of agent definitions and skills and it reports what a
person would otherwise find by reading every file: rules that exist in several
copies, rules that drifted apart, agents referenced by name that were never
written, skills that do the same job, and rules stamped with a date that nobody
has revisited.

None of these checks need traces or an LLM. They are properties of how the files
relate to each other, which is why this runs on day one, before any capture is
in place.

    python3 scripts/audit_structure.py <root>
    python3 scripts/audit_structure.py <root> --json report.json

Expected layout, which is also the layout this template proposes:

    <root>/<domain>/<agent>.md        one owner per domain
    <root>/<domain>/skills/<name>/SKILL.md
    <root>/shared/base.md             rules every agent obeys, one copy

It tolerates other shapes: any .md with YAML frontmatter carrying `name:` is
treated as an agent, and any SKILL.md as a skill.
"""

import argparse
import hashlib
import json
import re
import sys
from collections import Counter, defaultdict
from datetime import date, datetime
from pathlib import Path

# A rule stamped with a date and not revisited since is the symptom the pruning
# step exists to catch. Three months is a guess, and deliberately a visible one.
STALE_DAYS = 60

# How much of its text two copies of a heading must share before the heading
# reads as one rule in several places rather than a per-domain section that is
# supposed to differ. Measured on lines long enough to be a claim.
#
# A judgement knob, not a constant of nature. On the system this was built
# against, one rule repeated across five agents scored 0.34 while a genuinely
# per-domain section scored 0.00, so anything in that gap works. Raise it with
# --overlap if per-domain sections are being reported.
SHARED_OVERLAP = 0.25

DATE_PATTERNS = [
    re.compile(r"\((\d{4})-(\d{2})-(\d{2})\)"),
    re.compile(r"\b(\d{1,2})-(ene|feb|mar|abr|may|jun|jul|ago|sep|oct|nov|dic)-(\d{4})\b", re.I),
]
MONTHS = {m: i + 1 for i, m in enumerate(
    ["ene", "feb", "mar", "abr", "may", "jun", "jul", "ago", "sep", "oct", "nov", "dic"])}

# Words that would mean the system has some notion of retiring a rule.
PRUNING_SIGNALS = re.compile(
    r"\bdeprecat|\bobsolete|\bsunset|\bretire[sd]?\b|last confirmed|review by|"
    r"\bcaduca|revisar cada|expires on", re.I)

FRONTMATTER = re.compile(r"\A---\n(.*?)\n---\n", re.S)

# An agent assembled from one shared source says so in its own file. Identical
# sections across generated agents are identical BY CONSTRUCTION, which is the
# fix, not the defect: reporting them as duplication would tell someone their
# correct structure is wrong.
GENERATED = re.compile(r"GENERATED by [^\n]*build_agents", re.I)


def parse_frontmatter(text):
    m = FRONTMATTER.match(text)
    if not m:
        return {}
    out = {}
    for line in m.group(1).splitlines():
        if ":" in line and not line.startswith((" ", "\t", "-")):
            k, v = line.split(":", 1)
            out[k.strip()] = v.strip()
    return out


def sections(text):
    """Split markdown into {heading: body} for level-2 headings."""
    out, name, buf = {}, None, []
    for line in text.splitlines():
        if line.startswith("## "):
            if name is not None:
                out[name] = "\n".join(buf).strip()
            name, buf = line[3:].strip(), []
        elif name is not None:
            buf.append(line)
    if name is not None:
        out[name] = "\n".join(buf).strip()
    return out


def digest(text):
    return hashlib.md5(" ".join(text.split()).encode("utf-8")).hexdigest()[:8]


class Unreadable(Exception):
    pass


# macOS marks a file whose contents live only in the cloud with SF_DATALESS.
# Linux and Windows never set it, where the blocks check carries the case alone.
SF_DATALESS = 0x40000000


def is_local(path):
    """True when the file's bytes are on this disk.

    A file in iCloud Drive, Dropbox or OneDrive appears in the listing at full
    size while its contents live only in the cloud. Opening one blocks until the
    download finishes, and that wait happens inside an uninterruptible syscall:
    a timeout alarm never fires, so an audit that tries to read one does not
    fail, it hangs forever and looks like a broken tool.

    So the file is never opened. Both signals come from stat, which never
    blocks: a dataless file has no blocks allocated despite a non-zero size, and
    on macOS also carries SF_DATALESS.
    """
    try:
        st = path.stat()
    except OSError:
        return False
    if getattr(st, "st_flags", 0) & SF_DATALESS:
        return False
    return not (st.st_size > 0 and st.st_blocks == 0)


def read_guarded(path):
    """Read a file, or raise Unreadable if its contents are not on this disk."""
    if not is_local(path):
        raise Unreadable(str(path))
    return path.read_text(encoding="utf-8", errors="replace")


def is_agent(frontmatter):
    """An agent declares the tools or the model it runs with.

    `name` and `description` alone are not enough: memory notes, skill files and
    plenty of other documents carry those. Counting them turned a five-agent
    system into a hundred and thirty-four, and every per-agent number with it.
    What only an agent declares is how it runs.
    """
    if "name" not in frontmatter:
        return False
    if frontmatter.get("node_type") == "memory":
        return False
    return "tools" in frontmatter or "model" in frontmatter


def load(root):
    agents, skills, unreadable = {}, {}, []
    for path in sorted(root.rglob("*.md")):
        if any(p.startswith(".") for p in path.parts):
            continue
        # A .src.md is what a generated agent is built FROM. Counting both would
        # report every rule twice and halve the drift the audit is looking for.
        if path.name.endswith(".src.md"):
            continue
        try:
            text = read_guarded(path)
        except Unreadable:
            unreadable.append(str(path.relative_to(root)))
            continue
        if path.name == "SKILL.md":
            fm = parse_frontmatter(text)
            name = fm.get("name") or path.parent.name
            skills.setdefault(name, []).append(
                {"path": path, "text": text, "description": fm.get("description", "")})
            continue
        fm = parse_frontmatter(text)
        if is_agent(fm):
            agents[fm["name"]] = {"path": path, "text": text,
                                  "sections": sections(text), "frontmatter": fm,
                                  "generated": bool(GENERATED.search(text))}
    return agents, skills, unreadable


def line_overlap(bodies):
    """How much the copies of a section have in common, 0 to 1.

    Not the intersection of every copy: one agent rewording one line would drop
    that to zero, and a rule reworded per domain is exactly the case this has to
    recognise. Instead, the share of lines that appear in at least two copies.
    """
    sets = [{l.strip() for l in b.splitlines() if len(l.strip()) > 40} for b in bodies]
    sets = [s for s in sets if s]
    if len(sets) < 2:
        return 0.0
    counts = Counter(line for s in sets for line in s)
    repeated = sum(1 for n in counts.values() if n >= 2)
    average = sum(len(s) for s in sets) / len(sets)
    return repeated / average if average else 0.0


def shared_headings(root):
    """Headings the system has declared shared, by putting them in shared/base.md.

    This is what lets the audit tell a rule that drifted apart from a section
    that is supposed to differ. `## What you cover` differs per agent because
    each agent covers something different; `## Plan first` differing is a defect.
    A system with no shared file has declared nothing, so every repeated heading
    is a candidate and all of them get reported.
    """
    base = root / "shared" / "base.md"
    if not base.exists() or not is_local(base):
        return None
    return set(sections(base.read_text(encoding="utf-8", errors="replace")))


def check_duplicated_rules(agents, declared=None, overlap=SHARED_OVERLAP):
    """Sections that appear in more than one agent: identical, or drifted apart.

    Identical copies cost one edit per copy and the last one gets forgotten.
    Drifted copies are worse: the same heading now means different things, and a
    rule improved in one agent never reached the others.
    """
    where = defaultdict(dict)
    for name, agent in agents.items():
        for heading, body in agent["sections"].items():
            where[heading][name] = digest(body)

    identical, drifted, shared_ok = [], [], []
    for heading, copies in where.items():
        if len(copies) < 2:
            continue
        hashes = set(copies.values())
        row = {"heading": heading, "agents": sorted(copies),
               "copies": len(copies), "variants": len(hashes)}
        generated = all(agents[a].get("generated") for a in copies)
        row["declared"] = declared is None or heading in declared
        if generated and row["declared"]:
            shared_ok.append(row)
            continue
        if not row["declared"]:
            # Not in the shared file. Either a rule that has not been moved
            # there yet, or a section that is meant to differ per agent. The
            # copies say which: a rule keeps most of its lines across agents,
            # a per-domain section shares almost none.
            bodies = [agents[a]["sections"][heading] for a in copies]
            row["overlap"] = line_overlap(bodies)
            if row["overlap"] < overlap:
                continue
        if len(hashes) > 1:
            drifted.append(row)
        else:
            identical.append(row)
    key = lambda r: -r["copies"]
    return (sorted(identical, key=key),
            sorted(drifted, key=lambda r: -r["variants"]),
            sorted(shared_ok, key=key))


def check_unique_rules(agents, drifted):
    """Lines present in one agent's copy of a shared section and missing from the
    rest. This is the rule that was learned once and never propagated."""
    found = []
    for row in drifted:
        bodies = {a: agents[a]["sections"][row["heading"]] for a in row["agents"]}
        lines = {a: {l.strip() for l in b.splitlines() if len(l.strip()) > 40}
                 for a, b in bodies.items()}
        counts = Counter(l for own in lines.values() for l in own)
        for line, n in counts.items():
            if n < 2 or n == len(lines):
                continue  # unique to one agent, or already everywhere
            missing = sorted(a for a, own in lines.items() if line not in own)
            found.append({"heading": row["heading"],
                          "held_by": n, "of": len(lines),
                          "missing_from": missing, "line": line[:160]})
    return sorted(found, key=lambda r: -r["held_by"])


def check_dangling_agents(agents, skill_names=()):
    """Agents referenced by name in another agent's text but never defined."""
    known = set(agents)
    mentions = Counter()
    for name, agent in agents.items():
        for token in re.findall(r"`([a-z][a-z0-9-]{2,30})`", agent["text"]):
            if token != name:
                mentions[token] += 1
    # Build the corpus once: doing it per candidate turns this into a quadratic
    # scan over every agent file, which is slow enough to look like a hang.
    corpus = " ".join(a["text"] for a in agents.values())
    owner_words = re.compile(
        r"\b(agent|owner|owns|belongs|delegate|delega|dueño|pertenece)\b", re.I)
    # Collect the neighbourhood of every owner word once, then test candidates
    # against that much smaller string.
    neighbourhood = " ".join(
        corpus[max(0, m.start() - 60): m.end() + 60] for m in owner_words.finditer(corpus))

    known = known | set(skill_names)
    candidates = {}
    for token, count in mentions.items():
        if token in known or count < 2:
            continue
        if re.search(rf"\b{re.escape(token)}\b", neighbourhood, re.I):
            candidates[token] = count
    return candidates


def check_duplicate_skills(skills):
    """Skills registered more than once, and skills whose descriptions overlap
    enough that the model has to guess which one a request means."""
    multi = {n: [str(s["path"]) for s in v] for n, v in skills.items() if len(v) > 1}

    def words(text):
        return {w for w in re.findall(r"[a-z]{4,}", text.lower())}

    overlapping = []
    names = sorted(skills)
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            wa, wb = words(skills[a][0]["description"]), words(skills[b][0]["description"])
            if not wa or not wb:
                continue
            shared = len(wa & wb) / min(len(wa), len(wb))
            if shared >= 0.5:
                overlapping.append({"a": a, "b": b, "overlap": round(shared, 2)})
    return multi, sorted(overlapping, key=lambda r: -r["overlap"])


def check_stale_rules(agents, today):
    stamps = []
    for name, agent in agents.items():
        for pattern in DATE_PATTERNS:
            for m in pattern.finditer(agent["text"]):
                try:
                    if m.re is DATE_PATTERNS[0]:
                        d = date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
                    else:
                        d = date(int(m.group(3)), MONTHS[m.group(2).lower()], int(m.group(1)))
                except (ValueError, KeyError):
                    continue
                stamps.append({"agent": name, "date": d.isoformat(),
                               "age_days": (today - d).days})
    return sorted(stamps, key=lambda r: -r["age_days"])


def check_rules_file(root, today):
    """Read RULES.md, the ledger that makes step 07 possible.

    Each rule is a `###` heading followed by `- **field:** value` lines. Two
    things make a rule unmeasurable: no `from`, so there is no failure to watch
    for, and no `last confirmed`, so nobody knows whether it still earns its
    place. A rule confirmed long ago is the first candidate for removal.

    A system with no RULES.md has no ledger at all, which is reported as its own
    finding rather than as zero problems.
    """
    path = root / "RULES.md"
    if not path.exists() or not is_local(path):
        return None

    text = path.read_text(encoding="utf-8", errors="replace")
    rules, current = [], None
    for line in text.splitlines():
        # Rules leave through a "Removed" section; they are history, not the
        # live ledger, and anything under it is not counted as unmeasurable.
        if re.match(r"##\s+Removed\b", line, re.I):
            break
        if line.startswith("### "):
            current = {"name": line[4:].strip()}
            rules.append(current)
        elif current is not None:
            m = re.match(r"\s*[-*]\s*\*\*(.+?):\*\*\s*(.*)", line)
            if m:
                current[m.group(1).strip().lower()] = m.group(2).strip()

    def as_date(value):
        m = re.search(r"(\d{4})-(\d{2})-(\d{2})", value or "")
        if not m:
            return None
        try:
            return date(int(m.group(1)), int(m.group(2)), int(m.group(3)))
        except ValueError:
            return None

    out = []
    for r in rules:
        confirmed = as_date(r.get("last confirmed", ""))
        out.append({
            "name": r["name"],
            "status": r.get("status", "unstated"),
            "has_evidence": bool(r.get("from")),
            "last_confirmed": confirmed.isoformat() if confirmed else None,
            "age_days": (today - confirmed).days if confirmed else None,
        })
    return out


def check_pruning(agents, skills):
    hits = []
    for name, agent in agents.items():
        for m in PRUNING_SIGNALS.finditer(agent["text"]):
            hits.append({"where": name, "match": m.group(0)})
    for name, copies in skills.items():
        for m in PRUNING_SIGNALS.finditer(copies[0]["text"]):
            hits.append({"where": f"skill:{name}", "match": m.group(0)})
    return hits


def run(root, today=None, overlap=SHARED_OVERLAP):
    today = today or date.today()
    agents, skills, unreadable = load(root)
    declared = shared_headings(root)
    identical, drifted, shared_ok = check_duplicated_rules(agents, declared, overlap)
    multi, overlapping = check_duplicate_skills(skills)
    lines = sum(len(a["text"].splitlines()) for a in agents.values())
    lines += sum(len(v[0]["text"].splitlines()) for v in skills.values())
    return {
        "root": str(root),
        "shared_file": declared is not None,
        "unreadable": unreadable,
        "agents": {n: len(a["text"].splitlines()) for n, a in sorted(agents.items())},
        "skills": sorted(skills),
        "total_markdown_lines": lines,
        "shared_correctly": shared_ok,
        "identical_copies": identical,
        "drifted_copies": drifted,
        "unpropagated_rules": check_unique_rules(agents, drifted),
        "dangling_agents": check_dangling_agents(agents, skills),
        "skills_in_multiple_roots": multi,
        "overlapping_skills": overlapping,
        "dated_rules": check_stale_rules(agents, today),
        "pruning_mechanisms": check_pruning(agents, skills),
        "rules_ledger": check_rules_file(root, today),
    }


def report(r):
    out = []
    add = out.append
    add(f"AUDIT  {r['root']}")
    add(f"{len(r['agents'])} agents, {len(r['skills'])} skills, "
        f"{r['total_markdown_lines']} lines of markdown")
    if r["unreadable"]:
        add(f"  {len(r['unreadable'])} file(s) could not be read in time "
            f"(contents not on this disk); excluded from every count:")
        for f in r["unreadable"]:
            add(f"    {f}")
    for name, n in r["agents"].items():
        add(f"    {name:<16} {n:>5} lines")

    add("\n[05] PROPAGATE")
    if not r["shared_file"]:
        add("  no shared/base.md: nothing is declared shared, so every repeated")
        add("  section below is a candidate rather than a confirmed defect")
    if r["shared_correctly"]:
        add("  shared from one source, assembled into each agent:")
        for row in r["shared_correctly"]:
            add(f"    {row['copies']}x  {row['heading'][:60]}")
    if r["identical_copies"]:
        add("  identical copies of one section (one edit per copy):")
        for row in r["identical_copies"]:
            add(f"    {row['copies']}x  {row['heading'][:60]}")
    if r["drifted_copies"]:
        add("  same heading, different content (the expensive one):")
        for row in r["drifted_copies"]:
            mark = "" if row.get("declared") else "  <- not in shared/base.md yet"
            add(f"    {row['copies']} copies / {row['variants']} variants  "
                f"{row['heading'][:46]}{mark}")
    if r["unpropagated_rules"]:
        add(f"  rules that propagated partway: {len(r['unpropagated_rules'])}")
        for row in r["unpropagated_rules"][:6]:
            add(f"    {row['held_by']}/{row['of']} agents, missing from "
                f"{', '.join(row['missing_from'])}")
            add(f"      {row['line'][:110]}")
    if not (r["identical_copies"] or r["drifted_copies"] or r["shared_correctly"]):
        add("  no shared sections found")

    add("\n[07] MEASURE & PRUNE")
    ledger = r["rules_ledger"]
    if ledger is None:
        add("  no RULES.md: no rule records the failure that produced it, so no")
        add("  rule can be measured and none can be retired on evidence")
    else:
        unmeasurable = [x for x in ledger if not x["has_evidence"]]
        unconfirmed = [x for x in ledger if x["last_confirmed"] is None]
        stale_rules = [x for x in ledger
                       if x["age_days"] is not None and x["age_days"] > STALE_DAYS]
        add(f"  RULES.md holds {len(ledger)} rule(s)")
        if unmeasurable:
            add(f"    {len(unmeasurable)} with no `from`: no failure to watch for")
            for x in unmeasurable[:3]:
                add(f"      {x['name'][:60]}")
        if unconfirmed:
            add(f"    {len(unconfirmed)} never confirmed since being written")
            for x in unconfirmed[:3]:
                add(f"      {x['name'][:60]}")
        if stale_rules:
            add(f"    {len(stale_rules)} not confirmed in over {STALE_DAYS} days")
            for x in stale_rules[:3]:
                add(f"      {x['age_days']}d  {x['name'][:54]}")
    add(f"  pruning mechanisms found: {len(r['pruning_mechanisms'])}")
    stale = [d for d in r["dated_rules"] if d["age_days"] > STALE_DAYS]
    add(f"  dated rules: {len(r['dated_rules'])}, "
        f"{len(stale)} older than {STALE_DAYS} days")
    if r["dated_rules"]:
        oldest = r["dated_rules"][0]
        add(f"    oldest {oldest['date']} in {oldest['agent']} ({oldest['age_days']}d)")
    if r["skills_in_multiple_roots"]:
        add(f"  skills registered more than once: {len(r['skills_in_multiple_roots'])}")
    if r["overlapping_skills"]:
        add("  skills whose descriptions overlap (the model has to guess):")
        for row in r["overlapping_skills"][:5]:
            add(f"    {row['overlap']:.0%}  {row['a']} / {row['b']}")

    add("\n[04] ROUTE")
    if r["dangling_agents"]:
        add("  referenced as owners but never defined:")
        for name, n in sorted(r["dangling_agents"].items(), key=lambda x: -x[1]):
            add(f"    {name}  ({n} mentions)")
    else:
        add("  every agent referenced as an owner exists")
    return "\n".join(out)


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("root", type=Path, help="directory holding the agents")
    ap.add_argument("--json", type=Path, help="also write the full findings here")
    ap.add_argument("--overlap", type=float, default=SHARED_OVERLAP,
                    help="how much two copies of a heading must share before it "
                         f"counts as one rule rather than a per-domain section "
                         f"(default {SHARED_OVERLAP})")
    args = ap.parse_args(argv)

    if not args.root.is_dir():
        print(f"not a directory: {args.root}", file=sys.stderr)
        return 1
    r = run(args.root, overlap=args.overlap)
    print(report(r))
    if args.json:
        args.json.write_text(json.dumps(r, indent=2, ensure_ascii=False, default=str),
                             encoding="utf-8")
        print(f"\nfull findings: {args.json}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
