#!/usr/bin/env python3
"""Assemble each agent file from its own source plus the shared rules.

Step 05 of the loop. Shared rules pasted into every agent are the most common
cause of drift: four identical copies cost four edits and the fourth gets
forgotten, and five diverging copies mean a rule improved in one agent never
reaches the rest.

So `shared/base.md` holds the rules that apply to everyone, each
`agents/<domain>/<name>.src.md` holds only what is specific to that agent, and
this writes `agents/<domain>/<name>.md`, which is what the harness loads.

    python3 scripts/build_agents.py           # write the agent files
    python3 scripts/build_agents.py --check   # verify they match, change nothing

`--check` exits non-zero when a generated file has drifted from its source,
which is what a pre-commit hook runs.

Never edit a generated `<name>.md`: the next build overwrites it. Edit the
`.src.md` for one agent, or `shared/base.md` for all of them.

## Slots

Shared rules often need a domain-specific example: what this agent must not do
before a plan is approved, what counts as trivial for it. `shared/base.md` can
carry `{placeholders}`, and each source file fills them in a comment block:

    <!-- slots
    no_hacer:   edit a template, publish a page, or push CSS live
    trivial:    a one-line CSS fix, a copy tweak, a read-only answer
    -->

One rule, many wordings, no divergence. A placeholder with no matching slot is
left as-is and reported, rather than silently emptied.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
BASE = ROOT / "shared" / "base.md"
AGENT_DIR = ROOT / "agents"

BANNER = (
    "<!-- GENERATED by scripts/build_agents.py from {src} + shared/base.md.\n"
    "     Edit those, not this file: the next build overwrites it. -->\n"
)

SLOT_BLOCK = re.compile(r"<!--\s*slots\s*\n(.*?)-->\s*\n?", re.S)
PLACEHOLDER = re.compile(r"\{([a-z_][a-z0-9_]*)\}")


def split_frontmatter(body):
    """Return (frontmatter, rest).

    YAML frontmatter has to start at line 1 of the generated file. Put anything
    above it, including the banner, and the harness stops parsing `name`,
    `description` and `tools`: the agent silently stops registering, with no
    error raised anywhere.
    """
    if not body.startswith("---\n"):
        return "", body
    end = body.find("\n---\n", 4)
    if end == -1:
        return "", body
    return body[: end + 5], body[end + 5:]


def read_slots(body):
    """Pull the slot block out of a source file and return (slots, body)."""
    m = SLOT_BLOCK.search(body)
    if not m:
        return {}, body
    slots = {}
    for line in m.group(1).splitlines():
        if ":" in line:
            k, v = line.split(":", 1)
            slots[k.strip()] = v.strip()
    return slots, body[: m.start()] + body[m.end():]


def shared_block():
    text = BASE.read_text(encoding="utf-8")
    if text.lstrip().startswith("<!--"):
        text = text.split("-->", 1)[1]
    return text.strip("\n")


def fill(text, slots, name):
    missing = set()

    def sub(m):
        key = m.group(1)
        if key in slots:
            return slots[key]
        missing.add(key)
        return m.group(0)

    return PLACEHOLDER.sub(sub, text), sorted(missing)


def sources():
    return sorted(AGENT_DIR.glob("*/*.src.md"))


def assemble(src):
    body = src.read_text(encoding="utf-8").rstrip("\n")
    slots, body = read_slots(body)
    front, rest = split_frontmatter(body)
    shared, missing = fill(shared_block(), slots, src.stem)
    rel = src.relative_to(ROOT)
    banner = BANNER.format(src=rel)
    return f"{front}{banner}{rest.strip(chr(10))}\n\n{shared}\n", missing


def main(argv):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true",
                    help="verify the generated files match; write nothing")
    args = ap.parse_args(argv)

    if not BASE.exists():
        print(f"missing {BASE.relative_to(ROOT)}", file=sys.stderr)
        return 1
    found = sources()
    if not found:
        print(f"no *.src.md under {AGENT_DIR.relative_to(ROOT)}", file=sys.stderr)
        return 1

    stale = []
    for src in found:
        out = src.with_name(src.name.replace(".src.md", ".md"))
        built, missing = assemble(src)
        rel = out.relative_to(ROOT)
        if missing:
            print(f"  warn  {rel}: no slot for {', '.join(missing)}", file=sys.stderr)
        if args.check:
            current = out.read_text(encoding="utf-8") if out.exists() else ""
            ok = current == built
            print(f"{'ok' if ok else 'STALE':>5}  {rel}")
            if not ok:
                stale.append(str(rel))
        else:
            out.write_text(built, encoding="utf-8")
            print(f"wrote {rel}  ({len(built.splitlines())} lines)")

    if stale:
        print(f"\n{len(stale)} file(s) out of date, run without --check",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
